name: Deploy

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  deploy: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          python-version: 3.9

      - name: Get branch info
        shell: bash
        run: echo "##[set-output name=name;]$(echo ${GITHUB_REF##*/})"
        id: branch_info

      - name: Build hash list
        run: |
          cd ./script
          python3 hash.py ${{ steps.branch_info.outputs.name }}

      - name: Setup Ossutil
        uses: manyuanrong/setup-ossutil@v3.0
        with:
          endpoint: oss-cn-shanghai.aliyuncs.com
          access-key-id: ${{ secrets.OSS_ID }}
          access-key-secret: ${{ secrets.OSS_SECRET }}
      - name: Copy to Aliyun OSS
        run: |
          ossutil cp -rf vupslash oss://vupslash-test/
          ossutil cp -rf information.json oss://vupslash-test/
